import {Inter} from "next/font/google";
import {Providers} from "@/app/providers";
import { Link } from "@nextui-org/link";
import "@/styles/global.css";
import {Navbar} from "@/components/navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {


    return (
        <html lang="en" className="light">
        <body className={inter.className}>
        <Providers>
            <div className="relative flex flex-col h-screen">
                <Navbar/>
                <main className="container mx-auto max-w-7xl pt-10 px-6 flex-grow">
                    {children}
                </main>
                <footer className="w-full flex items-center justify-center py-3">
                    <Link
                        isExternal
                        className="flex items-center gap-1 text-current"
                        href="https://nextui-docs-v2.vercel.app?utm_source=next-app-template"
                        title="nextui.org homepage"
                    >
                        <span className="text-default-600">Made with ❤️ by BeViCi</span>
                    </Link>
                </footer>
            </div>
        </Providers>
        </body>
        </html>
    );
}
