import {Inter} from "next/font/google";
import {Providers} from "@/app/providers";
import "@/styles/global.css";
import {Navbar} from "@/components/navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {


    return (
        <html lang="en" className="light">
        <body className={inter.className}>
        <Providers>
            <div className="flex flex-col h-screen bg-gradient-to-r from-blue-400 to-blue-500">
                <Navbar/>
                <main className="container mx-auto pt-7 px-6 bg-gradient-to-r from-blue-400 to-blue-500">
                    {children}
                </main>
                <footer className="w-full flex items-center justify-center py-3 bg-gradient-to-r from-blue-400 to-blue-500">
                    <span className="text-white">Made with ❤️ by BeViCi</span>
                </footer>
            </div>
        </Providers>
        </body>
        </html>
    );
}
